// <auto-generated />
using KickCraze.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KickCraze.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231202182129_initLeague")]
    partial class initLeague
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KickCraze.Api.Entities.LeaguesEntity", b =>
                {
                    b.Property<int>("LeagueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueID"));

                    b.Property<string>("LeagueEmblemURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeagueID");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            LeagueID = 2021,
                            LeagueEmblemURL = "https://crests.football-data.org/PL.png",
                            LeagueName = "Premier League"
                        },
                        new
                        {
                            LeagueID = 2015,
                            LeagueEmblemURL = "https://crests.football-data.org/FL1.png",
                            LeagueName = "Ligue 1"
                        },
                        new
                        {
                            LeagueID = 2002,
                            LeagueEmblemURL = "https://crests.football-data.org/BL1.png",
                            LeagueName = "Bundesliga"
                        },
                        new
                        {
                            LeagueID = 2019,
                            LeagueEmblemURL = "https://crests.football-data.org/SA.png",
                            LeagueName = "Serie A"
                        },
                        new
                        {
                            LeagueID = 2014,
                            LeagueEmblemURL = "https://crests.football-data.org/PD.png",
                            LeagueName = "Primera Division"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
